version: '3'

services:
  php:
    build: php
    working_dir: /var/www/project
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./php/conf:/usr/local/etc/php/custom.d
      - ./project:/var/www/project
    environment:
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  nginx:
    image: nginx:alpine
    ports:
      - "2000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./project:/var/www/project
    depends_on:
      - php
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  redis:
    image: redis:alpine
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"