version: '2'

services:
  php-fpm:
    image: everyworkflow/php-fpm:latest
    #build: php-fpm
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./php-fpm/conf/php.ini:/usr/local/etc/php/php.ini
    volumes_from:
      - project-data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  php-cli:
    image: everyworkflow/php-cli:latest
    #build: php-cli
    working_dir: /var/www/project
    depends_on:
      - mongodb
      - redis
        #tty: true
    volumes_from:
      - project-data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  nginx:
    image: nginx:alpine
    ports:
      - "2000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
    depends_on:
      - php-fpm
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  redis:
    image: redis:alpine
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes_from:
      - mongo-data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  project-data:
    image: tianon/true
    volumes:
      - ./project:/var/www/project

  mongo-data:
    image: tianon/true
    volumes:
      - ./data/mongodb:/data/db
